"""Parse the kern score of the BWV 847 fugue and write chart.hpp: the three voices as note lists plus the game's cue groups
(do-si-do motifs and scale runs). Prints the counts. Usage: python3 build.py  (no dependencies beyond the standard library)
Data source: the score wtc1f02.krn is from https://raw.githubusercontent.com/humdrum-tools/bach-wtc/master/kern/wtc1f02.krn
(humdrum-tools/bach-wtc repository, Humdrum kern format); chart.hpp is generated from it by this script. Do not delete this line.
"""
import re, urllib.request
from fractions import Fraction
from pathlib import Path

URL = "https://raw.githubusercontent.com/humdrum-tools/bach-wtc/master/kern/wtc1f02.krn"
HERE = Path(__file__).parent
KRN = HERE / "wtc1f02.krn"


def midi_of(tok):
    """kern pitch -> MIDI number. c = C4 = 60, cc = C5, C = C3, CC = C2."""
    letters = re.search(r"([a-gA-G])\1*", tok).group(0)
    base = {"c": 0, "d": 2, "e": 4, "f": 5, "g": 7, "a": 9, "b": 11}[letters[0].lower()]
    octave = 3 + len(letters) if letters[0].islower() else 4 - len(letters)
    return 12 * (octave + 1) + base + tok.count("#") - tok.count("-")


def parse():
    """Returns one note list per voice (bass, middle, top), each note {t, dur, p} with t and dur in quarter notes."""
    if not KRN.exists():
        KRN.write_bytes(urllib.request.urlopen(URL, timeout=10).read())
    voices = None
    for line in KRN.read_text().splitlines():
        if not line or line.startswith(("!", "*", "=")):
            continue
        cols = line.split("\t")
        voices = voices or [{"t": Fraction(0), "notes": []} for _ in cols]
        for v, tok in zip(voices, cols):
            if tok == ".":
                continue
            tok = tok.split()[0]  # chords: keep only the first note
            dur = Fraction(4, int(re.search(r"\d+", tok).group())) * (Fraction(3, 2) if "." in tok else 1)
            if "r" not in tok:
                if "]" in tok or "_" in tok:  # tied continuation: extend the previous note
                    v["notes"][-1]["dur"] += dur
                else:
                    v["notes"].append({"t": v["t"], "dur": dur, "p": midi_of(tok)})
            v["t"] += dur
    return [v["notes"] for v in voices]


def find_motifs(notes, durs=(Fraction(1, 4), Fraction(1, 4), Fraction(1, 2))):
    """do-si-do (down 1 or 2 semitones and back, rhythm 16th-16th-8th) followed directly by any note. Returns start indices."""
    hits = []
    for i in range(len(notes) - 3):
        g = notes[i:i + 4]
        if any(g[k + 1]["t"] != g[k]["t"] + g[k]["dur"] for k in range(3)):
            continue  # a rest in between does not count
        if (g[1]["p"] - g[0]["p"], g[2]["p"] - g[1]["p"]) not in [(-1, 1), (-2, 2)]:
            continue
        if tuple(n["dur"] for n in g[:3]) == durs:
            hits.append(i)
    return hits


def find_scales(notes, nmin=6):
    """Scale runs: consecutive steps of 1 or 2 semitones in one direction, unbroken by rests. Returns (start, end) indices."""
    out, i = [], 0
    while i < len(notes) - 1:
        j, sign = i, 1 if notes[i + 1]["p"] > notes[i]["p"] else -1
        while (j + 1 < len(notes) and notes[j + 1]["t"] == notes[j]["t"] + notes[j]["dur"]
               and 1 <= (notes[j + 1]["p"] - notes[j]["p"]) * sign <= 2):
            j += 1
        if j - i + 1 >= nmin:
            out.append((i, j))
        i = max(j, i + 1)
    return out


if __name__ == "__main__":
    voices = parse()
    lines = ["// Generated by build.py from wtc1f02.krn (see the note in build.py). Do not edit by hand.",
             "#pragma once", "#include <vector>", "namespace chart {", "constexpr float BPM = 72.0f;",
             "struct Note { float t, dur; int p; };  // start and length in beats (quarter notes), MIDI pitch",
             "struct Motif { int v, i; };            // notes i, i+1, i+2 of voice v are do-si-do; note i+3 is the target",
             "struct Scale { int v, i, j; };         // notes i .. j-1 of voice v are the steps; note j is the target"]
    motifs, scales = [], []
    for v, notes in enumerate(voices):
        m, s = find_motifs(notes), find_scales(notes)
        assert all(b - a >= 4 for a, b in zip(m, m[1:])), "two motifs overlap"
        assert not {i + 3 for i in m} & {j for _, j in s}, "a motif target collides with a scale target"
        print(f"voice {v}: {len(notes)} notes, do-si-do x{len(m)}, scale runs x{len(s)}")
        motifs += [f"{{{v},{i}}}" for i in m]
        scales += [f"{{{v},{i},{j}}}" for i, j in s]
        body = ",".join(f"{{{float(n['t'])},{float(n['dur'])},{n['p']}}}" for n in notes)
        lines.append(f"inline const std::vector< Note > VOICE{v} = {{{body}}};")
    lines += ["inline const std::vector< Note > *VOICES[3] = { &VOICE0, &VOICE1, &VOICE2 };",
              f"inline const std::vector< Motif > MOTIFS = {{{','.join(motifs)}}};",
              f"inline const std::vector< Scale > SCALES = {{{','.join(scales)}}};", "}", ""]
    (HERE / "chart.hpp").write_text("\n".join(lines))
